liip_imagine:
    resolvers:
        default:
            web_path: ~
    filter_sets:
        thumb:
            quality: 75
            filters:
                thumbnail:
                    size: [360,230]
                    mode: outbound
        medium:
            quality: 75
            filters:
                thumbnail:
                    size: [460,330]
                    mode: outbound